# Neovim-Qt Experiments
# Azure Pipeline Continuous Integration
#
# Based on: https://github.com/microsoft/cpprestsdk/blob/master/azure-pipelines.yml

jobs:
  - job: Linux_Debug
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
        sudo apt install -y qt5-default
        sudo apt install -y neovim
        mkdir build
        /usr/local/bin/cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
        ninja
        displayName: Linux Debug Build
